In [4]:
import matplotlib.pyplot as plt
%matplotlib inline

import sep
import math
import keras
from keras.utils import np_utils
from keras.models import load_model

import numpy as np
from astropy.io import fits

import random 
import aplpy


from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

np.random.seed(123)  # for reproducibility

DOWNLOADING CNN MODEL 

In [5]:
model = load_model("CNNsingle.h5")


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



DOWNLOADING DATA

In [8]:
data_galaxy = np.load('datasets/galaxy_ic4559_images_scaled.npy')
labels_galaxy = np.load('datasets/galaxy_ic4559_labels_scaled.npy')

PREDICTION

In [10]:
labels_predict = model.predict(data_galaxy)

In [11]:
labels_predict2 = np.argmax(labels_predict, axis=-1)

In [12]:
accuracy_score(labels_galaxy, labels_predict2)

0.9921875

In [13]:
confusion_matrix(labels_galaxy, labels_predict2)

array([[315,   5],
       [  0, 320]])

In [15]:
def prediction (data, labels):
    labels_predict = model.predict(data)
    labels_predict2 = np.argmax(labels_predict, axis=-1)
    acc = accuracy_score(labels, labels_predict2)
    conf_mat = confusion_matrix(labels, labels_predict2)
    
    return acc, conf_mat
    

In [35]:
accuracy, matrix = prediction(data_galaxy, labels_galaxy)
print(matrix,accuracy)


[[315   5]
 [  0 320]] 0.9921875


In [34]:
data_galaxy_pgc21577 = np.load('datasets/galaxy_pgc21577_images_scaled.npy')
labels_galaxy_pgc21577 = np.load('datasets/galaxy_pgc21577_labels_scaled.npy')
accuracy2, matrix2 = prediction(data_galaxy_pgc21577, labels_galaxy_pgc21577)
print(matrix2,accuracy2)


[[405   5]
 [  2 408]] 0.9914634146341463


In [33]:
data_galaxy_pgc21708 = np.load('datasets/galaxy_pgc21708_images_scaled.npy')
labels_galaxy_pgc21708 = np.load('datasets/galaxy_pgc21708_labels_scaled.npy')
accuracy3, matrix3 = prediction(data_galaxy_pgc21708, labels_galaxy_pgc21708)
print(matrix3,accuracy3)

[[339   7]
 [  3 343]] 0.9855491329479769


In [32]:
data_galaxy_pgc21747 = np.load('datasets/galaxy_pgc21747_images_scaled.npy')
labels_galaxy_pgc21747 = np.load('datasets/galaxy_pgc21747_labels_scaled.npy')
accuracy4, matrix4 = prediction(data_galaxy_pgc21747, labels_galaxy_pgc21747)
print(matrix4, accuracy4)

[[317  11]
 [  1 327]] 0.9817073170731707


In [41]:
data_galaxy_pgc21856 = np.load('datasets/galaxy_pgc21856_images_scaled.npy')
labels_galaxy_pgc21856 = np.load('datasets/galaxy_pgc21856_labels_scaled.npy')
accuracy5, matrix5 = prediction(data_galaxy_pgc21856, labels_galaxy_pgc21856)
print(matrix5, accuracy5)

[[277   4]
 [  0 281]] 0.9928825622775801


In [64]:
def merging_datasets(d1,l1,d2,l2,d3,l3,d4,l4,d5,l5):
    
           
    dataset = np.append(d1,d2, axis=0)
    dataset2 = np.append(dataset,d3, axis=0)
    dataset3 = np.append(dataset2,d4, axis=0)
    dataset4 = np.append(dataset3,d5, axis=0)

    labels = np.append(l1,l2, axis=0)
    labels2 = np.append(labels,l3, axis=0)
    labels3 = np.append(labels2,l4, axis=0)
    labels4 = np.append(labels3,l5, axis=0)
    
    
    return dataset4, labels4

In [65]:
data, lab = merging_datasets(data_galaxy, labels_galaxy, data_galaxy_pgc21577, labels_galaxy_pgc21577, data_galaxy_pgc21708, labels_galaxy_pgc21708, data_galaxy_pgc21747, labels_galaxy_pgc21747, data_galaxy_pgc21856, labels_galaxy_pgc21856)

In [66]:
print(prediction(data, lab))

(0.9887240356083086, array([[1653,   32],
       [   6, 1679]]))
