In [2]:
import matplotlib.pyplot as plt
%matplotlib inline

import sep
import math
import keras
from keras.utils import np_utils
from keras.models import load_model

import numpy as np
from astropy.io import fits

import random 
import aplpy


from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

np.random.seed(123)  # for reproducibility

Using TensorFlow backend.


DOWNLOADING CNN MODEL 

In [3]:
model = load_model("NNdouble.h5")

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



DOWNLOADING DATA

In [4]:
data_galaxy = np.load('datasets/galaxy_ic4559_images_scaled.npy')
labels_galaxy = np.load('datasets/galaxy_ic4559_labels_scaled.npy')

PREDICTION

In [10]:
def prediction (data, labels):
    dataA = data[:,:,:,0]
    dataB = data[:,:,:,1]
    labels_predict = model.predict([dataA,dataB])
    labels_predict2 = np.argmax(labels_predict, axis=-1)
    acc = accuracy_score(labels, labels_predict2)
    conf_mat = confusion_matrix(labels, labels_predict2)
    
    return acc, conf_mat

In [6]:
dataA = data_galaxy[:,:,:,0]
dataB = data_galaxy[:,:,:,1]

labels_predict = model.predict([dataA,dataB])

In [7]:
labels_predict2 = np.argmax(labels_predict, axis=-1)

In [8]:
accuracy_score(labels_galaxy, labels_predict2)

0.99375

In [9]:
confusion_matrix(labels_galaxy, labels_predict2)

array([[317,   3],
       [  1, 319]])

In [21]:
acc, mat = prediction(data_galaxy, labels_galaxy)
print(mat,acc)

[[317   3]
 [  1 319]] 0.99375


In [20]:
data_galaxy_pgc21577 = np.load('datasets/galaxy_pgc21577_images_scaled.npy')
labels_galaxy_pgc21577 = np.load('datasets/galaxy_pgc21577_labels_scaled.npy')
accuracy2, matrix2 = prediction(data_galaxy_pgc21577, labels_galaxy_pgc21577)
print(matrix2,accuracy2)

[[387  23]
 [  5 405]] 0.9658536585365853


In [19]:
data_galaxy_pgc21708 = np.load('datasets/galaxy_pgc21708_images_scaled.npy')
labels_galaxy_pgc21708 = np.load('datasets/galaxy_pgc21708_labels_scaled.npy')
accuracy3, matrix3 = prediction(data_galaxy_pgc21708, labels_galaxy_pgc21708)
print(matrix3,accuracy3)


[[331  15]
 [  5 341]] 0.9710982658959537


In [22]:
data_galaxy_pgc21747 = np.load('datasets/galaxy_pgc21747_images_scaled.npy')
labels_galaxy_pgc21747 = np.load('datasets/galaxy_pgc21747_labels_scaled.npy')
accuracy4, matrix4 = prediction(data_galaxy_pgc21747, labels_galaxy_pgc21747)
print(matrix4, accuracy4)

[[296  32]
 [  0 328]] 0.9512195121951219


In [23]:
data_galaxy_pgc21856 = np.load('datasets/galaxy_pgc21856_images_scaled.npy')
labels_galaxy_pgc21856 = np.load('datasets/galaxy_pgc21856_labels_scaled.npy')
accuracy5, matrix5 = prediction(data_galaxy_pgc21856, labels_galaxy_pgc21856)
print(matrix5, accuracy5)

[[264  17]
 [  2 279]] 0.9661921708185054


In [27]:
def merging_datasets(d1,l1,d2,l2,d3,l3,d4,l4,d5,l5):
    
           
    dataset = np.append(d1,d2, axis=0)
    dataset2 = np.append(dataset,d3, axis=0)
    dataset3 = np.append(dataset2,d4, axis=0)
    dataset4 = np.append(dataset3,d5, axis=0)

    labels = np.append(l1,l2, axis=0)
    labels2 = np.append(labels,l3, axis=0)
    labels3 = np.append(labels2,l4, axis=0)
    labels4 = np.append(labels3,l5, axis=0)
    
    
    return dataset4, labels4

In [28]:
data, lab = merging_datasets(data_galaxy, labels_galaxy, data_galaxy_pgc21577, labels_galaxy_pgc21577, data_galaxy_pgc21708, labels_galaxy_pgc21708, data_galaxy_pgc21747, labels_galaxy_pgc21747, data_galaxy_pgc21856, labels_galaxy_pgc21856)

In [29]:
print(prediction(data, lab))

(0.9694362017804155, array([[1595,   90],
       [  13, 1672]]))


In [30]:
data.shape

(3370, 21, 21, 2)